name: automated_testing_framework_driver_websocket
description: Websock  et based driver for the automated testing framework.
version: 0.9.0
homepage: https://github.com/peiffer-innovations/automated_testing_framework_driver_websocket

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.6.0
  automated_testing_framework_models: ^1.0.7
  convert: ^2.1.1
  crypto: ^2.1.5
  json_class: ^1.0.7+2
  logging: ">=0.11.4 <2.0.0"
  meta: ^1.2.4
  uuid: ^2.2.2
  web_socket_channel: ^1.2.0

dev_dependencies:
  test: any
  test_coverage: any
# dependency_overrides:
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models
