name: automated_testing_framework_driver_websocket
description: Websocket based driver for the automated testing framework.
version: 1.0.1+1
homepage: https://github.com/peiffer-innovations/automated_testing_framework_driver_websocket

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  args: ^2.3.0
  automated_testing_framework_models: ^2.0.8+3
  convert: ^3.0.1
  crypto: ^3.0.1
  json_class: ^2.1.2+4
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.5
  web_socket_channel: ^2.1.0

dev_dependencies:
  test: ^1.20.1
# dependency_overrides:
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models
