name: automated_testing_framework_driver_websocket
description: Websocket based driver for the automated testing framework.
version: 0.9.5
homepage: https://github.com/peiffer-innovations/automated_testing_framework_driver_websocket

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  automated_testing_framework_models: ^2.0.0
  convert: ^3.0.0
  crypto: ^3.0.1
  json_class: ^2.0.0
  logging: ^1.0.1
  meta: ^1.3.0
  uuid: ^3.0.3
  web_socket_channel: ^2.0.0

dev_dependencies:
  test: any
# dependency_overrides:
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models
